### ISSUE TITLE
Server: Can't reach Vega B

### ISSUE THREAD

**Issue by LokeYourC3PH** [BlesseNtumble/GalaxySpace#20]
So in a Singleplayer game, i was able to reach Vega B with the T8 Rocket. The place where i landed had Barnarda F rock and biome, but outside that was blue Vega B biome. However, on my server, when i first started it (Vega B ID: -530), and tried to click and land on Vega B, i landed on Barnarda F. CoFH TPS showed me that 2 Barnarda F existed, for some odd reason. Then i changed the config, and made the ID -532, and now i cannot launch to Vega B at all, it does not let me. Clicking launch simply does nothing. Here my config:

http://pastebin.com/3C6TMv0H

Would be nice to get this fixed.

**Comment by LokeYourC3PH** [comment]
Now that i see it myself, is it possible to make Venus and Jupiter Space Stations? As they seem to be in the config, but in my server world folder, the last world ID is -524, which is Barnarda F, anything beyond that does not exist.

**Comment by LokeYourC3PH** [comment]
Wait so you know about it?

**Comment by BlesseNtumble** [comment]
Ok, Redownload build 1.0.8 and DELETE biome config file(or change biome for Kuiper Belt (<255))!!!!
I fixed "Exception ticking world" and fixed Vega B.

**Comment by Dream-Master** [comment]
Ok Thanks.
Will try it later.

**Comment by LokeYourC3PH** [comment]
Confirmed, downloading the update and deleting the biomes config file fixes this. Only one bug remaining.
